### ISSUE TITLE
Gradle version in "gradle-wrapper.properties" is old

### ISSUE THREAD

**Issue by TheJL-B** [experiandataquality/aperture-data-studio-sdk#8]
The gradle version in gradle-wrapper.properties is pretty old. The distribution URL needs to be updated distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip would suffice.

**Comment by yudhistira-arya** [comment]
I would suggest to add gradle wrapper task instead of modifying `gradle-wrapper.properties` directly since that file is auto-generated: 

```gradle
task createGradleWrapper(type: Wrapper) {
    gradleVersion = '4.9'
}
```

Please refer to [pull request #11](https://github.com/experiandataquality/aperture-data-studio-sdk/pull/11)
